# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField()),
                ('custumer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niokr.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Research_interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niokr.Expert')),
                ('research_interests_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niokr.Research_interests')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='research_interests_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niokr.Research_interests'),
        ),
        migrations.AddField(
            model_name='expert',
            name='research_interests_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niokr.Research_interests'),
        ),
    ]
