# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niokr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='login',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='password',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='expert',
            name='current_request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='niokr.Request'),
        ),
        migrations.AddField(
            model_name='expert',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='research_interests',
            name='name',
            field=models.CharField(choices=[(b'\xd0\x9e\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb1\xd0\xbe\xd1\x82\xd0\xba\xd0\xb0 \xd0\x9c\xd0\xb0\xd1\x82\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb\xd0\xbe\xd0\xb2', '\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0430 \u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u043e\u0432'), (b'\xd0\xa1\xd1\x82\xd1\x80\xd0\xbe\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe', '\u0421\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u043e'), (b'\xd0\xad\xd0\xbd\xd0\xb5\xd1\x80\xd0\xb3\xd0\xbe\xd0\xbe\xd0\xb1\xd0\xb5\xd1\x81\xd0\xbf\xd0\xb5\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5', '\u042d\u043d\u0435\u0440\u0433\u043e\u043e\u0431\u0435\u0441\u043f\u0435\u0447\u0435\u043d\u0438\u0435'), (b'IT', 'IT'), (b'\xd0\x9f\xd1\x80\xd0\xb8\xd0\xb1\xd0\xbe\xd1\x80\xd0\xbe\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5', '\u041f\u0440\u0438\u0431\u043e\u0440\u043e\u0441\u0442\u0440\u043e\u0435\u043d\u0438\u0435'), (b'\xd0\xad\xd0\xba\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb3\xd0\xb8\xd1\x8f', '\u042d\u043a\u043e\u043b\u043e\u0433\u0438\u044f')], default=b'IT', max_length=50),
        ),
    ]
