# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niokr', '0003_auto_20151221_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='expert_id',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='research_interests_id',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
