# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niokr', '0004_auto_20151223_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='organization',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
