# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niokr', '0005_auto_20151223_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='current_request_id',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='research_interests_id',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='user',
        ),
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441'),
        ),
        migrations.AlterField(
            model_name='request',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='request',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='request',
            name='organization',
            field=models.CharField(max_length=50, null=True, verbose_name='\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(max_length=50, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='request',
            name='position',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='request',
            name='research_interests_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='niokr.Research_interests', verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='request',
            name='short_description',
            field=models.TextField(null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0437\u0430\u044f\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='research_interests',
            name='name',
            field=models.CharField(choices=[('\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0430 \u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u043e\u0432', '\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0430 \u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u043e\u0432'), ('\u0421\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u043e', '\u0421\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u043e'), ('\u042d\u043d\u0435\u0440\u0433\u043e\u043e\u0431\u0435\u0441\u043f\u0435\u0447\u0435\u043d\u0438\u0435', '\u042d\u043d\u0435\u0440\u0433\u043e\u043e\u0431\u0435\u0441\u043f\u0435\u0447\u0435\u043d\u0438\u0435'), ('IT', 'IT'), ('\u041f\u0440\u0438\u0431\u043e\u0440\u043e\u0441\u0442\u0440\u043e\u0435\u043d\u0438\u0435', '\u041f\u0440\u0438\u0431\u043e\u0440\u043e\u0441\u0442\u0440\u043e\u0435\u043d\u0438\u0435'), ('\u042d\u043a\u043e\u043b\u043e\u0433\u0438\u044f', '\u042d\u043a\u043e\u043b\u043e\u0433\u0438\u044f')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Expert',
        ),
    ]
