# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niokr', '0006_auto_20151223_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='research_interests_id',
        ),
        migrations.DeleteModel(
            name='Research_interests',
        ),
    ]
