# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niokr', '0009_auto_20151225_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='current_request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niokr.Request', verbose_name='\u0422\u0435\u043a\u0443\u0449\u0430\u044f \u0437\u0430\u044f\u0432\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='request',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='research_interests_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niokr.Research_interests', verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c'),
        ),
    ]
