# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niokr', '0010_auto_20151225_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0430'),
        ),
    ]
