# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niokr', '0011_auto_20160214_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='address',
        ),
        migrations.RemoveField(
            model_name='request',
            name='email',
        ),
        migrations.RemoveField(
            model_name='request',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='request',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='request',
            name='position',
        ),
    ]
