# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niokr', '0013_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niokr.Client', verbose_name='\u0412\u0430\u0448\u0435 \u0438\u043c\u044f'),
        ),
    ]
